### PR TITLE
Statsd integration + Tomcat redeploy fix for PeriodicalLog

### PR DESCRIPTION
**Pull request by pcting**
Two things in this pull request:
- I added a StatsdLog which will allow speed4j to emit statsd metrics
- c_factories is set to null at the end of StopWatchFactory.shutdown() so that Tomcat can redeploy the application and also reinitialize speed4j in the process.

### CODE REVIEW

**Comment by jalkanen** [comment]
Yah, I think that just adding the license would be sufficient. Thanks!

**Comment by mailsurfie** [comment]
is this feature included in the trunk source? and should this issue be closed?

**Comment by pcting** [comment]
no, i've been lazy about reformatting the code to be accepted. i'll try to spend time on it; it'll probably only be an hour's worth of work.

**Comment by pcting** [comment]
i finally got around to pinging the statsd guys:
https://github.com/etsy/statsd/issues/122

we'll know whether we can use the code soon

**Comment by mrtazz** [comment]
Isn't the MIT license compatible with the ASL? From what I've read so far, it should be ok to use it within the project. Or is that a specific project restriction?

**Comment by pcting** [comment]
@jalkanen will you be okay if i tacked on the MIT license instead of ASL for just the StatsdClient.java file?

**Comment by jalkanen** [comment]
MIT license is fine!

**Comment by pcting** [comment]
@jalkanen I adjusted the commits to fit the coding style and added the MIT license to the top of the StatsdClient class.

**Comment by jalkanen** [comment]
Thank you :-)

**Pull request merged**
